"""Summarize compiler warnings and measured test phases from CI logs or ZIPs."""

import argparse
from collections import Counter
import json
from pathlib import Path
import re
from zipfile import ZipFile


WARNING = re.compile(r"((?:src|tests)[/\\].+?)\((\d+),(\d+)\): warning (CS\d+): (.*?)(?: \[.*\])?$")
PHASE = re.compile(r"ticks=(\d+) frequency=(\d+) pid=(\d+) thread=\d+ test=(.*?) stage=(\S+)")
SIGNALS = {
    "objc_duplicate_class": "Class ExtensionDropdownHandler is implemented in both",
    "shader_compile_timeout": "Compilation took longer than",
    "gpu_initialization_exit": "Exiting GPU process due to errors during initialization",
    "mach_rendezvous_failure": "Mach rendezvous failed",
}


def logs(path):
    if path.suffix == ".zip":
        with ZipFile(path) as archive:
            for name in archive.namelist():
                if name.endswith(".log"):
                    yield f"{path.name}/{name}", archive.read(name).decode("utf-8-sig")
    elif path.is_dir():
        for child in sorted(path.rglob("*.log")):
            yield str(child), child.read_text(encoding="utf-8-sig")
    else:
        yield str(path), path.read_text(encoding="utf-8-sig")


def summarize(entries, root):
    warnings = {}
    intervals = []
    signals = []
    for name, contents in entries:
        phases = {}
        counts = Counter()
        for line in contents.splitlines():
            match = WARNING.search(line)
            if match:
                file, row, column, code, message = match.groups()
                file = file.replace("\\", "/")
                key = (file, int(row), int(column), code)
                if key not in warnings:
                    source = root / file
                    generated = None
                    if source.is_file():
                        with source.open(encoding="utf-8-sig") as stream:
                            generated = "<auto-generated" in stream.read(2048).lower()
                    warnings[key] = dict(file=file, line=int(row), column=int(column), code=code, message=message, generated_marker=generated, occurrences=0)
                warnings[key]["occurrences"] += 1
            # stdout repeats these records; only the dedicated phase file is authoritative.
            if Path(name).name.startswith("test-phases-"):
                match = PHASE.search(line)
                if match:
                    ticks, frequency, pid, test, stage = match.groups()
                    key = (pid, test)
                    phases.setdefault(key, []).append((int(ticks), int(frequency), stage))
            if name.endswith((".stderr.log", "cef-tests.log")):
                for signal, text in SIGNALS.items():
                    if text in line:
                        counts[signal] += 1
        for (_, test), records in phases.items():
            # Threads capture timestamps before acquiring the synchronized writer.
            records.sort(key=lambda record: record[0])
            for previous, current in zip(records, records[1:]):
                old_ticks, old_frequency, old_stage = previous
                ticks, frequency, stage = current
                if frequency != old_frequency:
                    raise ValueError(f"Invalid monotonic phase timestamps in {name}")
                intervals.append(dict(log=name, test=test, start=old_stage, end=stage, seconds=(ticks - old_ticks) / frequency))
        if counts:
            signals.append(dict(log=name, matching_lines=dict(counts)))
    ordered = [warnings[key] for key in sorted(warnings)]
    return dict(
        unique_warning_count=len(ordered),
        warnings_by_code=dict(sorted(Counter(item["code"] for item in ordered).items())),
        warnings=ordered,
        slowest_phase_intervals=sorted(intervals, key=lambda item: item["seconds"], reverse=True)[:50],
        native_log_signals=signals,
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", nargs="+", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    if any(not path.exists() for path in args.inputs):
        parser.error("Every input path must exist.")
    if args.output.exists() or not args.output.parent.is_dir():
        parser.error("The output must be new and its parent must exist.")
    report = summarize((entry for path in args.inputs for entry in logs(path)), Path(__file__).resolve().parents[2])
    with args.output.open("x", encoding="utf-8") as output:
        json.dump(report, output, ensure_ascii=False, indent=2)
    if args.output.stat().st_size == 0:
        raise RuntimeError("Missing diagnostics summary")
    print(f"Unique warnings: {report['unique_warning_count']}; by code: {report['warnings_by_code']}")
    for phase in report["slowest_phase_intervals"][:10]:
        print(f"{phase['seconds']:.3f}s {phase['test']}: {phase['start']} -> {phase['end']}")
    print(f"Diagnostics: {args.output.resolve()}")


if __name__ == "__main__":
    main()
