<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <!-- 禁止项目通过 VersionOverride 私自覆盖中央版本 -->
        <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
        <AvaloniaVersion>11.3.20</AvaloniaVersion>
        <ReactiveUIAvaloniaVersion>11.4.13</ReactiveUIAvaloniaVersion>
        <CefRedistVersion>120.1.8</CefRedistVersion>
        <CefRedistOSXVersion>120.1.8</CefRedistOSXVersion>
        <CefRedistLinuxVersion>120.1.8</CefRedistLinuxVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="ReactiveUI.Avalonia" Version="$(ReactiveUIAvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Dotnet.Bundle" Version="0.9.13" />
        <PackageVersion Include="System.Reactive" Version="6.1.0" />
        <PackageVersion Include="chromiumembeddedframework.runtime" Version="$(CefRedistVersion)" />
        <PackageVersion Include="chromiumembeddedframework.runtime.win-x64" Version="$(CefRedistVersion)" />
        <PackageVersion Include="chromiumembeddedframework.runtime.win-arm64" Version="$(CefRedistVersion)" />
        <PackageVersion Include="cef.redist.linux64" Version="$(CefRedistLinuxVersion)" />
        <PackageVersion Include="cef.redist.linuxarm64" Version="$(CefRedistLinuxVersion)" />
        <PackageVersion Include="cef.redist.osx64" Version="$(CefRedistOSXVersion)" />
        <PackageVersion Include="cef.redist.osx.arm64" Version="$(CefRedistOSXVersion)" />
        <PackageVersion Include="nunit" Version="4.6.1" />
        <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageVersion Include="NLog" Version="6.2.0" />
    </ItemGroup>
</Project>
