<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <!-- 可选：禁止项目通过 VersionOverride 私自覆盖中央版本 -->
        <CentralPackageVersionOverrideEnabled>true</CentralPackageVersionOverrideEnabled>
        <MicrosoftExtensionsVersion>10.0.11</MicrosoftExtensionsVersion>
        <AvaloniaVersion>11.3.20</AvaloniaVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="CefSharp.OffScreen.NETCore" Version="151.3.170" />
    </ItemGroup>
</Project>
