<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug_WindowlessRender'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework.Legacy.ClassicAssert" Alias="Assert" />
    <Using Include="NUnit.Framework.Legacy.CollectionAssert" Alias="CollectionAssert" />
    <Using Include="NUnit.Framework.Legacy.StringAssert" Alias="StringAssert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CefGlue.Common.Shared\CefGlue.Common.Shared.csproj" />
    <ProjectReference Include="..\..\src\CefGlue.Common\CefGlue.Common.csproj" />
    <ProjectReference Include="..\..\src\CefGlue\CefGlue.csproj" />
  </ItemGroup>

</Project>
