<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <AssemblyName>Xilium.CefGlue.BrowserProcess</AssemblyName>
    <RootNamespace>Xilium.CefGlue.BrowserProcess</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- 只生成可移植的 managed DLL，不生成平台相关 apphost-->
    <UseAppHost>false</UseAppHost>
    <!-- 不把 .NET Runtime 自己打进去，而是依赖目标机器已有的 .NET Runtime-->
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ObjectBinding\CefGlueGlobalScript.js" />
    <EmbeddedResource Include="ObjectBinding\CefGlueGlobalScript.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefGlue.Common.Shared\CefGlue.Common.Shared.csproj" />
    <ProjectReference Include="..\CefGlue\CefGlue.csproj" />
  </ItemGroup>
</Project>
