<Project>
    <PropertyGroup>
        <!--BrowserProcess 现在是 portable managed assets，所以不再有 win-x64/linux-x64/... 子目录。-->
        <CefGlueBrowserProcessAssetsPath Condition="'$(CefGlueBrowserProcessAssetsPath)' == ''">$(MSBuildThisFileDirectory)..\tools\browser-process\</CefGlueBrowserProcessAssetsPath>
    </PropertyGroup>
</Project>
