<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework.Legacy.ClassicAssert" Alias="Assert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CefGlue.WPF\CefGlue.WPF.csproj" />
    <ProjectReference Include="..\..\src\CefGlue.Common\CefGlue.Common.csproj" />
    <ProjectReference Include="..\..\src\CefGlue\CefGlue.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TestInfrastructure\CefRunContextMenuCallbackHarness.cs" Link="TestInfrastructure\CefRunContextMenuCallbackHarness.cs" />
    <Compile Include="../TestInfrastructure/TestProgressAttribute.cs" Link="TestInfrastructure/TestProgressAttribute.cs" />
  </ItemGroup>

</Project>
