<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework.Legacy.ClassicAssert" Alias="Assert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CefGlue.WPF\CefGlue.WPF.csproj" />
  </ItemGroup>

</Project>
